<?php
	/*
	 * addDesktopIcon.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			#horizontal .addDesktopIconBox{float:left;}
			#sprite_horizontal .addDesktopIconBox{float:left;}
		</style>
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

				addDesktopIcon(document.getElementById('horizontal'), '/tmp/adddesktopicon.png', '/desktop.html', 'Icon label', '#000');
				addDesktopIcon(document.getElementById('horizontal'), '/tmp/adddesktopicon.png', null, 'Icon label', '#000');
				addDesktopIcon(document.getElementById('vertical'), '/tmp/adddesktopicon.png', '/desktop.html', 'Icon label', '#000');
				addDesktopIcon(document.getElementById('vertical'), '/tmp/adddesktopicon.png', null, 'Icon label', '#000');
				addDesktopSpriteIcon(document.getElementById('sprite_horizontal'), '/tmp/adddesktopiconsprite.png', '33px', '/desktop.html', 'Icon label', '#000');
				addDesktopSpriteIcon(document.getElementById('sprite_horizontal'), '/tmp/adddesktopiconsprite.png', '66px', null, 'Icon label', '#000');
				addDesktopSpriteIcon(document.getElementById('sprite_vertical'), '/tmp/adddesktopiconsprite.png', '33px', '/desktop.html', 'Icon label', '#000');
				addDesktopSpriteIcon(document.getElementById('sprite_vertical'), '/tmp/adddesktopiconsprite.png', '66px', null, 'Icon label', '#000');
			});
		</script>
	</head>
	<body>
		<h1>Horizontal</h1>
		<div id="horizontal"></div>
		<br><br><br><br>
		<h1>Vertical</h1>
		<div id="vertical"></div>
		<h1>Sprite Horizontal</h1>
		<div id="sprite_horizontal"></div>
		<br><br><br><br>
		<h1>Sprite Vertical</h1>
		<div id="sprite_vertical"></div>
	</body>
</html>