<?php
	/*
	 * beautify.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

				beautify('ass', '@$$');
				beautify('cunt', ['c*t', 'c***', '@#$%']);
			});
		</script>
	</head>
	<body>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
	</body>
</html>