<?php
	/*
	 * epilepsi.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			#epileptic_square {
				width: 500px;
				height: 500px;
			}
		</style>
		<script>
			<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

			document.addEventListener('DOMContentLoaded', function(){
				flashBackground('epileptic_square', 1000, 'black', 'pink', 'blue', 'red');
				flashText('expileptic_text', 500, 'white', 'red', 'purple', 'orange');
			}, false)
		</script>
	</head>
	<body>
		<div id="epileptic_square">
			<h1 id="expileptic_text">Epileptic text</h1>
		</div>
	</body>
</html>