<?php
	/*
	 * fadeAnimationIn.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<!--[if !IE]><!--><style>body{opacity:0}</style><noscript><style>body{opacity:1}</style></noscript><!--<![endif]-->
		<script>
			alert('START');

			<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>
		</script>
	</head>
	<body>
		<h1>Text</h1>
	</body>
</html>