<?php
	/*
	 * fadeAnimationOut.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}

	sleep(1);
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

			function refreshPage()
			{
				window.location.reload();
			}

			document.addEventListener('DOMContentLoaded', function(){
				setTimeout(refreshPage, 1000);
			}, false);
		</script>
	</head>
	<body>
		<h1>Text</h1>
	</body>
</html>