<?php
	/*
	 * getCookie.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

				document.cookie='test_cookie=good_value';

				if(getCookie('test_cookie') === 'good_value')
					document.body.innerHTML='<h1>Success</h1>';
				else
					document.body.innerHTML='<h1>Fail</h1>';
			}, false)
		</script>
	</head>
	<body></body>
</html>