<?php
	/*
	 * imgRotator.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

				imgRotator(document.getElementById('myimgtag'), 1000, ['/img1.png', '/img2.png', '/img3.png']);
			}, false);
		</script>
	</head>
	<body>
		<img id="myimgtag" src="/tmp/imgrotator.png">
	</body>
</html>