<?php
	/*
	 * titleScroller.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 */

	if(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
	{
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file';
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>titleScroller.js library test |</title>
		<script>
			<?php include __DIR__.'/../lib/'.basename(__FILE__, '.phtml'); ?>

			document.addEventListener('DOMContentLoaded', function(){
				titleScroller();
			}, false)
		</script>
	</head>
	<body></body>
</html>