<?php
	$GLOBALS['login']['csp_header']['default-src'][]='\'none\'';
	$GLOBALS['login']['csp_header']['script-src'][]='\'self\'';
	$GLOBALS['login']['csp_header']['connect-src'][]='\'self\'';
	$GLOBALS['login']['csp_header']['img-src'][]='\'self\'';
	$GLOBALS['login']['csp_header']['style-src'][]='\'self\'';
	$GLOBALS['login']['csp_header']['base-uri'][]='\'self\'';
	$GLOBALS['login']['csp_header']['form-action'][]='\'self\'';
?>