<?php
	/*
	 * addDesktopIcon.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 *
	 * Warning:
	 *  gd extension is recommended
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}

	if(extension_loaded('gd'))
	{
		@mkdir(__DIR__.'/tmp/addDesktopIcon');

		if(!file_exists(__DIR__.'/tmp/addDesktopIcon/adddesktopicon.png'))
		{
			$image=imagecreate(32, 32);
			imagecolorallocate($image, 0,0,0);
			imagefilledarc($image, 16,16, 32,32, 0,360, imagecolorallocate($image, 255,255,255), IMG_ARC_PIE);
			imagepng($image, __DIR__.'/tmp/addDesktopIcon/adddesktopicon.png');
			imagedestroy($image);
		}

		if(!file_exists(__DIR__.'/tmp/addDesktopIcon/adddesktopiconsprite.png'))
		{
			$image=imagecreate(64, 32);
			imagecolorallocate($image, 0,0,0);
			imagefilledarc($image, 16,16, 32,32, 0,360, imagecolorallocate($image, 255,255,255), IMG_ARC_PIE);
			imagefilledarc($image, 49,16, 32,32, 0,360, imagecolorallocate($image, 255,0,0), IMG_ARC_PIE);
			imagepng($image, __DIR__.'/tmp/addDesktopIcon/adddesktopiconsprite.png');
			imagedestroy($image);
		}
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self' 'nonce-stylemain'; script-src 'self' 'nonce-scriptmain'; img-src 'self'">
		<style nonce="stylemain">
			#horizontal .addDesktopIconBox
			{
				float: left;
			}
			#sprite_horizontal .addDesktopIconBox
			{
				float: left;
			}
		</style>
		<script nonce="scriptmain">
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				addDesktopIcon(
					document.getElementById('horizontal'),
					'/tmp/addDesktopIcon/adddesktopicon.png',
					'/desktop.html',
					'Icon label',
					'#000'
				);
				addDesktopIcon(
					document.getElementById('horizontal'),
					'/tmp/addDesktopIcon/adddesktopicon.png',
					null,
					'Icon label',
					'#000'
				);
				addDesktopIcon(
					document.getElementById('vertical'),
					'/tmp/addDesktopIcon/adddesktopicon.png',
					'/desktop.html',
					'Icon label',
					'#000'
				);
				addDesktopIcon(
					document.getElementById('vertical'),
					'/tmp/addDesktopIcon/adddesktopicon.png',
					null,
					'Icon label',
					'#000'
				);
				addDesktopSpriteIcon(
					document.getElementById('sprite_horizontal'),
					'/tmp/addDesktopIcon/adddesktopiconsprite.png',
					'33px',
					'/desktop.html',
					'Icon label',
					'#000'
				);
				addDesktopSpriteIcon(
					document.getElementById('sprite_horizontal'),
					'/tmp/addDesktopIcon/adddesktopiconsprite.png',
					'66px',
					null,
					'Icon label',
					'#000'
				);
				addDesktopSpriteIcon(
					document.getElementById('sprite_vertical'),
					'/tmp/addDesktopIcon/adddesktopiconsprite.png',
					'33px',
					'/desktop.html',
					'Icon label',
					'#000'
				);
				addDesktopSpriteIcon(
					document.getElementById('sprite_vertical'),
					'/tmp/addDesktopIcon/adddesktopiconsprite.png',
					'66px',
					null,
					'Icon label',
					'#000'
				);
			}, false);
		</script>
	</head>
	<body>
		<h1>Horizontal</h1>
		<div id="horizontal"></div>
		<br><br><br><br>

		<h1>Vertical</h1>
		<div id="vertical"></div>

		<h1>Sprite Horizontal</h1>
		<div id="sprite_horizontal"></div>
		<br><br><br><br>

		<h1>Sprite Vertical</h1>
		<div id="sprite_vertical"></div>
	</body>
</html>