<?php
	/*
	 * beautify.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				beautify(document.body, 'ass', '@$$');
				beautify(document.body, 'cunt', ['c*t', 'c***', '@#$%']);
			}, false);
		</script>
	</head>
	<body>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
		<span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span> <span style="color: #ff0000;">ass</span> <span style="color: #00ff00;">cunt</span> <span style="color: #0000ff;">text</span>
	</body>
</html>