<?php
	/*
	 * button.css library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>
		</style>
	</head>
	<body>
		<?php
			foreach(['blue', 'dark'] as $color)
			foreach(['', 'button_black_text_shadow', 'button_white_text_shadow'] as $text_shadow)
			foreach(['', 'button_blue_border', 'button_dark_border'] as $border)
			foreach(['', 'button_blue_hover', 'button_dark_hover'] as $hover)
			foreach(['', 'full_width'] as $width)
			foreach(['slim', 'big', 'circle'] as $mode)
			{
				$classes=''
				.	'button '
				.	'button_'.$width.' '
				.	'button_'.$color.' '
				.	'button_'.$mode.' '
				.	$border.' '
				.	$hover.' '
				.	$text_shadow;

				foreach([
					'',
					'button_shadow',
					'button_hover',
					'button_border',
					'button_text_shadow',
					'button_right'
				] as $class){
					$classes.=' '.$class;

					echo $classes;
					?>
						<br><br>
						<div class="<?php echo $classes; ?>">Button label</div>
						<hr>
					<?php
				}
			}
		?>
	</body>
</html>