<?php
	/*
	 * clock.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<?php if(isset($_GET['clock'])) { ?><script>
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>

			document.addEventListener('DOMContentLoaded', function(){<?php
				switch($_GET['clock'])
				{
					case 'clockDigital': ?>
						clockDigital('clock_div_id', ':');
					<?php break;
					case 'clockDigitalImage': ?>
						clockDigitalImage(
							'clock_div_id',
							[
								'/tmp/clock/0.png',
								'/tmp/clock/1.png',
								'/tmp/clock/2.png',
								'/tmp/clock/3.png',
								'/tmp/clock/4.png',
								'/tmp/clock/5.png',
								'/tmp/clock/6.png',
								'/tmp/clock/7.png',
								'/tmp/clock/8.png',
								'/tmp/clock/9.png'
							],
							'/tmp/clock/separator.png'
						);
					<?php break;
					case 'clockDigitalImageSprite': ?>
						clockDigitalImageSprite(
							'clock_div_id',
							'/tmp/clock/clock.png',
							'24px',
							'16px',
							'8px',
							[
								'0px',
								'16px',
								'32px',
								'48px',
								'64px',
								'80px',
								'96px',
								'112px',
								'128px',
								'144px'
							],
							'160px'
						);
					<?php break;
					case 'clockAnalogCSS': ?>
						clockAnalogCSS('clock_div_id', '#000000');
					<?php break;
					case 'clockAnalogImage': ?>
						clockAnalogImage(
							'clock_div_id',
							[
								'/tmp/clock/clock-face.png',
								'/tmp/clock/hour-hand.png',
								'/tmp/clock/minute-hand.png',
								'/tmp/clock/second-hand.png',
								'/tmp/clock/top-image.png'
							]
						);
					<?php break;
					case 'clockAnalogImageSprite': ?>
						clockAnalogImageSprite(
							'clock_div_id',
							'/tmp/clock/clockspriteanalog.png',
							['400px', '800px', '1200px', '1600px']
						);
					<?php break;
				}
			?>}, false);
		</script><?php } ?>
	</head>
	<body>
		<?php
			if(isset($_GET['clock']))
				switch($_GET['clock'])
				{
					case 'clockDigital': ?>
						<h1><div id="clock_div_id"></div></h1>
					<?php break;
					case 'clockDigitalImage':
					case 'clockDigitalImageSprite': ?>
						<div id="clock_div_id"></div>
					<?php break;
					case 'clockAnalogCSS':
					case 'clockAnalogImage':
					case 'clockAnalogImageSprite': ?>
						<div id="clock_div_id" style="width: 500px; height: 500px;"></div>
					<?php break;
				}
			else
			{ ?>
				<div style="font-size: 30pt;">
					<a href="?clock=clockDigital">clockDigital</a><br>
					<a href="?clock=clockDigitalImage">clockDigitalImage</a><br>
					<a href="?clock=clockDigitalImageSprite">clockDigitalImageSprite</a><br>
					<a href="?clock=clockAnalogCSS">clockAnalogCSS</a><br>
					<a href="?clock=clockAnalogImage">clockAnalogImage</a><br>
					<a href="?clock=clockAnalogImageSprite">clockAnalogImageSprite</a>
				</div>
				<?php }
		?>
	</body>
</html>