<?php
	/*
	 * disableEnterOnForm.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				disableEnterOnForm(document.getElementById('disable-enter-here'));
			}, false);
		</script>
	</head>
	<body>
		When you press enter while typing, nothing should happen.
		<br>
		<form>
			<input id="disable-enter-here" type="text">
			<input type="submit">
		</form>
	</body>
</html>