<?php
	/*
	 * epilepsi.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self' 'nonce-stylemain'; script-src 'self' 'nonce-scriptmain'">
		<style nonce="stylemain">
			#epileptic_square {
				width: 500px;
				height: 500px;
			}
		</style>
		<script nonce="scriptmain">
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>

			document.addEventListener('DOMContentLoaded', function(){
				flashBackground(
					document.getElementById('epileptic_square'),
					1000,
					'black', 'pink', 'blue', 'red'
				);

				flashText(
					document.getElementById('expileptic_text'),
					500,
					'white', 'red', 'purple', 'orange'
				);
			}, false)
		</script>
	</head>
	<body>
		<div id="epileptic_square">
			<h1 id="expileptic_text">Epileptic text</h1>
		</div>
	</body>
</html>