<?php
	/*
	 * fadeAnimationOut.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}

	sleep(1);
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>

			function refreshPage()
			{
				window.location.reload();
			}

			document.addEventListener('DOMContentLoaded', function(){
				setTimeout(refreshPage, 1000);
			}, false);
		</script>
	</head>
	<body>
		<h1>Text</h1>
	</body>
</html>