<?php
	/*
	 * getCssJs.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}

	@mkdir(__DIR__.'/tmp');
	foreach(['getCssJs.css', 'getCssJs.js'] as $file)
		@unlink(__DIR__.'/tmp/'.$file);

	file_put_contents(__DIR__.'/tmp/getCssJs.css', ''
	.	'body {'
	.	'	color: #ffffff;'
	.	'	background-color: #000000;'
	.	'}'
	);
	file_put_contents(
		__DIR__.'/tmp/getCssJs.js',
		'document.getElementById("getjs").innerHTML="getJS works";'."\n"
	);
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				getCSS('/tmp/getCssJs.css');
				getJS('/tmp/getCssJs.js');
			});
		</script>
	</head>
	<body>
		<h1>Text color: white</h1>
		<h1>Background color: black</h1>
		<h1 id="getjs">getJS is not working</h1>
	</body>
</html>