<?php
	/*
	 * pfReplaceAll.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				if(typeof String.prototype.replaceAll !== 'undefined')
					delete String.prototype.replaceAll;

				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				document.getElementById('output-text').innerHTML=document.getElementById('source-text').innerHTML.replaceAll('dog', 'monkey');

				if(document.getElementById('output-text').innerHTML.trim() === 'The quick brown fox jumps over the lazy monkey. If the monkey reacted, was it really lazy?')
					document.getElementById('test-result').innerHTML='Test passed';
			});
		</script>
	</head>
	<body>
		<h2>Replace "dog" with "monkey"</h2>
		<h3>Source:</h3>
		<div id="source-text">
			The quick brown fox jumps over the lazy dog. If the dog reacted, was it really lazy?
		</div>
		<h3>Output:</h3>
		<div id="output-text">
			Test failed
		</div>
		<h3 id="test-result">Test failed</h3>
	</body>
</html>