<?php
	/*
	 * print_file.php library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}

	if(!is_file(__DIR__.'/tmp/print_file.png'))
	{
		echo 'Put file in '.__DIR__.'/tmp/print_file.png';
		exit();
	}

	if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
		require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
	else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
		require __DIR__.'/../'.basename(__FILE__, '.phtml');

	print_file(__DIR__.'/tmp/print_file.png', 3600);
?>