<?php
	/*
	 * print_file.php library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 *
	 * Warning:
	 *  gd extension is recommended
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}

	if(!is_file(__DIR__.'/tmp/print_file/print_file.png'))
	{
		if(extension_loaded('gd'))
		{
			@mkdir(__DIR__.'/tmp/print_file');

			$image=imagecreate(32, 32);
			imagecolorallocate($image, 0,0,0);
			imagefilledarc($image, 16,16, 32,32, 0,360, imagecolorallocate($image, 0,255,0), IMG_ARC_PIE);
			imagepng($image, __DIR__.'/tmp/print_file/print_file.png');
			imagedestroy($image);
		}
		else
		{
			echo 'Put file in '.__DIR__.'/tmp/print_file/print_file.png';
			exit();
		}
	}

	if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
		require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
	else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
		require __DIR__.'/../'.basename(__FILE__, '.phtml');

	print_file(__DIR__.'/tmp/print_file/print_file.png', [
		'cache'=>3600
	]);
?>