<?php
	/*
	 * richTextEditor.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			#richTextEditorBox,
			#richTextEditorBoxWithoutCallbacks {
				border: 1px solid black;
			}
			#richTextEditorBox textarea,
			#richTextEditorBoxWithoutCallbacks textarea {
				height: 400px;
				width: 100%;
				resize: none;
				border: none;
				outline: none;
			}
		</style>
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				richTextEditor(document.getElementById('richTextEditorBox'), 'richTextEditorOutput', {
					'sourceId': 'richTextEditorOutput', // textarea id
					'content': 'Initial content', // JSON encoded string
					'height': '400px', // same as in styles
					'linkCallback': function()
					{
						return 'https://google.com';
					},
					'imgCallback': function()
					{
						return [
							'http://localhost:8080/image.jpg',
							'Alternate text'
						];
					},
					'fontColorCallback': function()
					{
						return 'blue';
					},
					'backColorCallback': function()
					{
						return '#ff0000';
					},
					'buttonLabels': {
						'bold': 'Grube',
						'italic': 'Włoskie',
						'underline': 'Podkreślome',
						'left': 'Lewe',
						'center': 'Środkowe',
						'right': 'Prawe',
						'paragraph': 'Paragraf',
						'addLink': 'Link',
						'removeLink': 'Usuń link',
						'addImg': 'Obrazek',
						'addOl': 'Lista numerowana',
						'addUl': 'Lista nienumerowana',
						'src': 'Źródło',
						'heading': 'Nagłówek',
						'fontSize': 'Wielkość czcionki',
						'fColor': 'Kolor czcionki',
						'bColor': 'Kolor tła',
						'removeFormat': 'Usuń formatowanie'
					}
				});

				richTextEditor(document.getElementById('richTextEditorBoxWithoutCallbacks'), 'richTextEditorOutputWithoutCallbacks', {
					'sourceId': 'richTextEditorOutputWithoutCallbacks', // textarea id
					'height': '400px' // same as in styles
				});
			}, false);
		</script>
	</head>
	<body>
		<h1>PHP input</h1>
		<div>
			<?php
				if(isset($_GET['richTextEditorOutput']))
					echo $_GET['richTextEditorOutput'];

				echo '<hr>';

				if(isset($_GET['richTextEditorOutputWithoutCallbacks']))
					echo $_GET['richTextEditorOutputWithoutCallbacks'];
			?>
		</div>
		<hr>
		<form action="" method="GET">
			<h1>With callbacks</h1>
			<div id="richTextEditorBox">
				<textarea name="richTextEditorOutput">Initial content</textarea>
			</div>

			<h1>Without callbacks</h1>
			<div id="richTextEditorBoxWithoutCallbacks">
				<textarea name="richTextEditorOutputWithoutCallbacks">Initial content</textarea>
			</div>

			<input type="submit">
		</form>
	</body>
</html>