<?php
	/*
	 * simpleblog_materialized.css library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>

			input[type=file]::before {
				content: 'Add files';
			}
		</style>
	</head>
	<body<?php if(isset($_GET['action']) && ($_GET['action'] === 'pagealt')) echo ' class="sbc_white sbbc_black"'; ?>>
		<?php if(!isset($_GET['action'])) { ?>
			<div style="margin-top: 20px; margin-left: 20px;">
				<a href="?action=blog" style="font-size: 25pt;">Blog</a>
				<br><br>
				<a href="?action=page" style="font-size: 25pt;">Page</a>
				<br><br>
				<a href="?action=pagealt" style="font-size: 25pt;">Page (alternative colors)</a>
				<br><br>
				<a href="?action=colors" style="font-size: 25pt;">Colors</a>
			</div>
		<?php } else if($_GET['action'] === 'blog') { ?>
			<div id="header" class="sb_header"><h1>HEADER HEADER</h1></div>
			<div id="headlinks" class="sb_headlinks">
				<div class="headlink sb_headlink"><a href="#">Current</a><div class="headlink_active sb_headlink_active"></div></div>
				<div class="headlink sb_headlink"><a href="#">Another</a></div>
			</div>
			<div id="page" class="sb_page">
				<div class="article sb_article">
					<div class="article_title sb_article_title">
						ARTICLE TITLE
						<div class="article_date sb_article_date">
							ARTICLE DATE
						</div>
					</div>
					<div class="article_content sb_article_content">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. In urna odio, semper vel odio at, sagittis ultricies sem. Mauris scelerisque, sem at venenatis finibus, lacus ex malesuada quam, quis pharetra massa odio consectetur velit. Sed odio est, venenatis sit amet efficitur nec, varius id lectus. Donec blandit nisi nec viverra mattis. Aliquam sed placerat augue. Nullam feugiat consectetur urna, vitae porta lectus imperdiet at. Quisque ut dolor maximus, mattis erat nec, ornare ante. In vitae nisi sed sem auctor porttitor.
						Vestibulum sollicitudin, eros sed facilisis cursus, nunc lorem elementum metus, at maximus nibh diam vehicula nulla. Fusce varius turpis sed gravida scelerisque. Curabitur ornare mi eu metus commodo ullamcorper. Nunc vel scelerisque nunc, id fermentum nibh. Donec sit amet accumsan odio. Nam condimentum eget velit eu volutpat. Mauris vitae dapibus metus, accumsan rhoncus leo. Praesent sit amet placerat ligula. Vivamus tincidunt, augue quis convallis iaculis, urna elit fringilla magna, ut consectetur urna justo non metus. Praesent vel justo sed orci placerat dictum in id nisl. Morbi eget urna justo.
						Donec lobortis nisl diam, vitae eleifend orci ornare id. Nullam nisi ligula, viverra vel quam vitae, laoreet efficitur ex. In interdum rhoncus sapien eu accumsan. Aliquam at leo id nibh pharetra cursus ut sed odio. Nulla id diam vitae libero vulputate commodo sit amet eget risus. Suspendisse hendrerit purus ac ipsum sollicitudin fringilla. Nulla rhoncus, dui quis fringilla tincidunt, elit ipsum finibus urna, in condimentum massa tortor eu elit. Quisque nec sem vel nibh posuere posuere nec non enim. Duis sed velit malesuada, lacinia libero eu, venenatis ante. Proin molestie molestie velit, vel ullamcorper ex eleifend sed. Etiam tincidunt tincidunt mi, vel ultrices enim lobortis eget. Curabitur nisi nunc, interdum eu tortor sed, tristique egestas est. Duis vestibulum mattis fermentum. Aenean congue porta porttitor. Donec euismod orci et eros porta, maximus tristique dolor congue.
						Nam vel faucibus nunc, quis placerat nisi. Nullam at eros eget dui semper dictum non id ipsum. In malesuada consectetur tortor, ac gravida ligula posuere ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id sodales magna. Pellentesque rhoncus sem eu dolor malesuada maximus. In congue ligula quis lectus cursus consectetur. In quis ante eros. Nam vel posuere turpis. Quisque a tempus libero. Fusce blandit velit vitae vehicula pulvinar. Pellentesque feugiat odio hendrerit, ultricies libero a, volutpat sem. Morbi consectetur est ex, nec tempus est vestibulum ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet sapien ut ipsum tincidunt dapibus et eu enim. Fusce tortor metus, aliquet sit amet mollis vel, suscipit sed tellus.
						Duis imperdiet vulputate velit in pulvinar. Nulla viverra ac elit vel malesuada. Ut non purus id elit laoreet porttitor fringilla vel arcu. Cras id purus ac tellus pellentesque scelerisque in quis mi. Duis cursus nec enim quis vestibulum. Aliquam sed lacus fermentum, commodo odio ut, tempor neque. In et sagittis dolor. Nam tellus ex, auctor ut nulla eu, tincidunt scelerisque ante. Mauris quis ante eget dolor consectetur interdum. Etiam lectus tortor, vestibulum sed consequat nec, vestibulum nec elit. Mauris aliquam aliquam molestie.
						Nunc viverra congue nisl sit amet porta. Aenean accumsan lobortis lacus vel scelerisque. Morbi eleifend quam nibh, vel suscipit lacus commodo nec. Phasellus aliquet odio ac mauris posuere tempus. Vestibulum condimentum nulla at quam fermentum egestas non at dolor. Ut sit amet mattis purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent volutpat dui id elit pretium congue. Pellentesque ac interdum ligula.
						Nullam in nunc sit amet purus mattis volutpat. Aenean gravida non mi ac lobortis. Nulla ac turpis accumsan, commodo ipsum eget, placerat sapien. Nullam nec quam id turpis dignissim ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae enim id risus pulvinar porttitor. Duis hendrerit elit sit amet felis aliquam finibus. Vestibulum ac viverra lacus, consequat dictum lorem. Nulla ornare rutrum erat sit amet tempor. Ut mauris nunc, aliquet ac lorem quis, maximus tempor nisi. Aenean turpis felis, pharetra non est et, venenatis consequat erat. Duis tempus accumsan lorem quis porttitor.
						Nunc in vulputate dui, nec finibus enim. In dignissim, turpis vel finibus ultricies, nisl nunc dignissim mi, et porta massa ipsum at turpis. Nunc et neque in nisi fringilla dignissim. Etiam maximus gravida condimentum. Phasellus vel eros lacus. Fusce sit amet eros ac sapien accumsan rutrum. Duis at libero eget nibh imperdiet pharetra. Maecenas dictum vehicula metus non eleifend. Proin tempus leo magna, vitae placerat ligula scelerisque quis. Aliquam vehicula turpis faucibus nisi posuere, eget volutpat neque mollis. Etiam nec fermentum odio. Ut placerat vestibulum lorem.
						Fusce mollis quis nibh eget tincidunt. Praesent pharetra bibendum arcu a iaculis. Nam malesuada rhoncus mauris at ultricies. Sed eget tempor ex. Curabitur laoreet tristique risus et luctus. Duis tincidunt velit dictum, aliquam justo eget, tincidunt ex. Donec id efficitur est, non sodales neque. Vivamus venenatis odio non vulputate suscipit. Nam rhoncus elit vel orci faucibus, vitae euismod mi accumsan. Sed ultrices eu enim in rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam aliquam neque a ligula fermentum, eu vestibulum nisi convallis.
						Fusce congue accumsan elit, non aliquam odio porta pharetra. Aenean vitae fringilla tortor, non euismod augue. Aliquam at quam sed augue viverra sagittis sit amet at mauris. Etiam fermentum enim risus, ut egestas orci rhoncus quis. Proin elementum tincidunt sapien mollis sagittis. Praesent ut neque sit amet justo laoreet finibus. Maecenas elit sapien, ultrices in diam quis, suscipit cursus eros. Donec a eros sed elit ullamcorper maximus. In hac habitasse platea dictumst. Ut vestibulum augue et lectus scelerisque, a ornare dui porta. Ut volutpat sed nisl sed ultricies. Etiam porttitor orci vitae tincidunt sodales.
						Donec iaculis eros eu posuere feugiat. Suspendisse id ultrices dui. Cras elementum neque at urna scelerisque vehicula. Nunc congue orci nec dapibus pharetra. Quisque convallis sollicitudin mi vitae pretium. Donec justo ex, interdum id neque nec, dictum rhoncus dolor. Sed bibendum elit eget rutrum pellentesque. Mauris in ullamcorper lacus, ut elementum magna. In sit amet purus eu ipsum porttitor sagittis. Phasellus mauris mauris, sollicitudin id ornare non, vulputate finibus ligula. Phasellus mollis tempor quam ut facilisis. Cras justo sem, dictum vel nisi sit amet, vehicula ornare libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
						Vivamus rhoncus purus vitae nunc euismod, quis tristique justo vehicula. Quisque elementum quam leo, at vulputate lacus malesuada vel. Suspendisse commodo, tortor vitae dapibus imperdiet, urna enim sollicitudin tellus, vitae facilisis ligula arcu id ligula. Donec pellentesque, mi at condimentum molestie, massa enim ultricies ante, at sollicitudin enim felis ac dolor. Aliquam ac aliquam lectus. Maecenas dictum nisl lectus, sed hendrerit nibh fermentum sit amet. Quisque posuere turpis quis neque scelerisque sagittis vel dapibus libero. Praesent at nisi lacus. Fusce vulputate, dui at porttitor blandit, est felis placerat massa, sit amet sodales quam dui id velit.
						Phasellus odio orci, gravida eu lectus sit amet, aliquam elementum nulla. Sed felis lacus, semper in interdum et, tincidunt sed purus. Sed accumsan massa ex, at rhoncus nibh malesuada ac. Nulla ac ligula a odio iaculis convallis. Sed vitae dapibus libero, eu luctus felis. In vitae nunc volutpat, molestie ligula a, semper justo. Vestibulum mattis quis ex a semper. Proin semper vehicula ullamcorper. Etiam ac vestibulum neque. In euismod, diam sed posuere faucibus, velit risus dignissim ante, nec bibendum orci urna sit amet sapien. Nunc bibendum lectus eget velit dictum, quis venenatis sapien semper.
						Donec egestas dapibus ipsum sed ornare. Vestibulum ut tellus sit amet turpis tristique molestie quis sed erat. Proin suscipit lacus sed ipsum sodales consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed cursus rhoncus diam eu tempus. Aliquam aliquam convallis ligula, at auctor dolor tincidunt vitae. Donec volutpat condimentum enim, vel blandit nunc tincidunt a. Suspendisse eget feugiat felis. Proin quis ipsum odio. In at elit at nibh consequat varius
						Aliquam ornare vitae neque sed pellentesque. Nulla eget congue diam. Aenean et varius mauris, eget blandit magna. Aenean pellentesque, neque faucibus auctor hendrerit, erat leo consequat mauris, ac consectetur purus ante in sem. Nullam consectetur volutpat consequat. Ut finibus cursus ipsum, eu malesuada lacus luctus vel. Vivamus in tellus lobortis, vestibulum dolor id, rutrum lectus. Donec blandit, velit vel pulvinar mattis, orci neque ultrices augue, commodo sagittis sapien massa eu quam. Proin a felis quis felis consequat efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet neque lobortis, mollis mi porttitor, maximus tellus. Phasellus a ultricies augue. Maecenas in felis orci. Quisque ullamcorper tincidunt quam eget iaculis. Cras posuere hendrerit neque sit amet placerat. Morbi metus dolor, rutrum sed eros auctor, accumsan laoreet justo.
						Nullam consectetur eget tellus sed lacinia. Ut sed dignissim enim, eget tempus sapien. Aenean quis turpis vitae lorem fringilla blandit quis ac diam. Sed at massa rutrum, commodo massa a, fringilla risus. Sed dictum tincidunt diam, id tristique urna hendrerit at. Vivamus velit nisl, porttitor id feugiat eget, blandit vitae metus. Etiam accumsan odio ipsum, quis pulvinar enim rhoncus at. Phasellus vitae auctor ligula.
						Proin in lectus in velit euismod malesuada vitae vel ante. Nulla nisi risus, sodales at rutrum nec, euismod at purus. In efficitur nunc finibus molestie ultricies. Etiam nec lacus ligula. Ut ac nisl luctus, posuere ex vitae, maximus mi. Duis sapien nulla, ornare a finibus sed, lobortis id tellus. Curabitur massa lorem, maximus non commodo vitae, sodales non quam. Pellentesque id quam lacus. Phasellus posuere non quam eu vestibulum. Vestibulum eu ornare nulla. Duis est turpis, dictum quis rhoncus ut, scelerisque in nulla.
						Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin luctus lacinia sollicitudin. Praesent sed molestie ex. Nam non mauris eros. Nullam sit amet magna luctus, vulputate ipsum at, gravida est. Donec in hendrerit sapien. Sed a tortor mauris. Morbi varius faucibus ligula, in rhoncus tortor blandit ultrices. Donec venenatis nisl nulla, sit amet ultricies tortor dapibus eu. Duis mi lectus, vulputate id metus in, consequat vestibulum diam. Ut faucibus est a convallis porta.
						Curabitur eu ex vitae leo suscipit pulvinar non vitae augue. Aliquam pharetra mattis mauris sit amet maximus. Cras sed tristique odio. In venenatis auctor iaculis. Aenean in orci maximus eros vulputate varius sed vitae orci. Curabitur vel rutrum lectus. In vitae pellentesque urna, aliquam mattis lectus. Etiam lacinia ligula id dui porttitor bibendum.
						Phasellus fringilla est tellus, eget laoreet tellus placerat convallis. Mauris in sollicitudin diam. Aenean eu malesuada risus. Pellentesque at sagittis lectus. Proin ullamcorper tortor nec nisl iaculis, at aliquam nunc commodo. Cras ut commodo lacus. Suspendisse ac mollis mauris, in mattis ipsum. Etiam cursus sapien in ipsum tincidunt, et commodo sapien faucibus. Sed id ipsum ut nunc fermentum facilisis. Aliquam a nulla magna. Vestibulum fermentum viverra dolor sed posuere. Phasellus mi turpis, feugiat quis libero ac, tincidunt accumsan arcu.
					</div>
				</div>
				<div class="article sb_article">
					<div class="article_title sb_article_title">
						ARTICLE TITLE
						<div class="article_date sb_article_date">
							ARTICLE DATE
						</div>
					</div>
					<div class="article_content sb_article_content">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. In urna odio, semper vel odio at, sagittis ultricies sem. Mauris scelerisque, sem at venenatis finibus, lacus ex malesuada quam, quis pharetra massa odio consectetur velit. Sed odio est, venenatis sit amet efficitur nec, varius id lectus. Donec blandit nisi nec viverra mattis. Aliquam sed placerat augue. Nullam feugiat consectetur urna, vitae porta lectus imperdiet at. Quisque ut dolor maximus, mattis erat nec, ornare ante. In vitae nisi sed sem auctor porttitor.
						Vestibulum sollicitudin, eros sed facilisis cursus, nunc lorem elementum metus, at maximus nibh diam vehicula nulla. Fusce varius turpis sed gravida scelerisque. Curabitur ornare mi eu metus commodo ullamcorper. Nunc vel scelerisque nunc, id fermentum nibh. Donec sit amet accumsan odio. Nam condimentum eget velit eu volutpat. Mauris vitae dapibus metus, accumsan rhoncus leo. Praesent sit amet placerat ligula. Vivamus tincidunt, augue quis convallis iaculis, urna elit fringilla magna, ut consectetur urna justo non metus. Praesent vel justo sed orci placerat dictum in id nisl. Morbi eget urna justo.
						Donec lobortis nisl diam, vitae eleifend orci ornare id. Nullam nisi ligula, viverra vel quam vitae, laoreet efficitur ex. In interdum rhoncus sapien eu accumsan. Aliquam at leo id nibh pharetra cursus ut sed odio. Nulla id diam vitae libero vulputate commodo sit amet eget risus. Suspendisse hendrerit purus ac ipsum sollicitudin fringilla. Nulla rhoncus, dui quis fringilla tincidunt, elit ipsum finibus urna, in condimentum massa tortor eu elit. Quisque nec sem vel nibh posuere posuere nec non enim. Duis sed velit malesuada, lacinia libero eu, venenatis ante. Proin molestie molestie velit, vel ullamcorper ex eleifend sed. Etiam tincidunt tincidunt mi, vel ultrices enim lobortis eget. Curabitur nisi nunc, interdum eu tortor sed, tristique egestas est. Duis vestibulum mattis fermentum. Aenean congue porta porttitor. Donec euismod orci et eros porta, maximus tristique dolor congue.
						Nam vel faucibus nunc, quis placerat nisi. Nullam at eros eget dui semper dictum non id ipsum. In malesuada consectetur tortor, ac gravida ligula posuere ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id sodales magna. Pellentesque rhoncus sem eu dolor malesuada maximus. In congue ligula quis lectus cursus consectetur. In quis ante eros. Nam vel posuere turpis. Quisque a tempus libero. Fusce blandit velit vitae vehicula pulvinar. Pellentesque feugiat odio hendrerit, ultricies libero a, volutpat sem. Morbi consectetur est ex, nec tempus est vestibulum ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet sapien ut ipsum tincidunt dapibus et eu enim. Fusce tortor metus, aliquet sit amet mollis vel, suscipit sed tellus.
						Duis imperdiet vulputate velit in pulvinar. Nulla viverra ac elit vel malesuada. Ut non purus id elit laoreet porttitor fringilla vel arcu. Cras id purus ac tellus pellentesque scelerisque in quis mi. Duis cursus nec enim quis vestibulum. Aliquam sed lacus fermentum, commodo odio ut, tempor neque. In et sagittis dolor. Nam tellus ex, auctor ut nulla eu, tincidunt scelerisque ante. Mauris quis ante eget dolor consectetur interdum. Etiam lectus tortor, vestibulum sed consequat nec, vestibulum nec elit. Mauris aliquam aliquam molestie.
						Nunc viverra congue nisl sit amet porta. Aenean accumsan lobortis lacus vel scelerisque. Morbi eleifend quam nibh, vel suscipit lacus commodo nec. Phasellus aliquet odio ac mauris posuere tempus. Vestibulum condimentum nulla at quam fermentum egestas non at dolor. Ut sit amet mattis purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent volutpat dui id elit pretium congue. Pellentesque ac interdum ligula.
						Nullam in nunc sit amet purus mattis volutpat. Aenean gravida non mi ac lobortis. Nulla ac turpis accumsan, commodo ipsum eget, placerat sapien. Nullam nec quam id turpis dignissim ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae enim id risus pulvinar porttitor. Duis hendrerit elit sit amet felis aliquam finibus. Vestibulum ac viverra lacus, consequat dictum lorem. Nulla ornare rutrum erat sit amet tempor. Ut mauris nunc, aliquet ac lorem quis, maximus tempor nisi. Aenean turpis felis, pharetra non est et, venenatis consequat erat. Duis tempus accumsan lorem quis porttitor.
						Nunc in vulputate dui, nec finibus enim. In dignissim, turpis vel finibus ultricies, nisl nunc dignissim mi, et porta massa ipsum at turpis. Nunc et neque in nisi fringilla dignissim. Etiam maximus gravida condimentum. Phasellus vel eros lacus. Fusce sit amet eros ac sapien accumsan rutrum. Duis at libero eget nibh imperdiet pharetra. Maecenas dictum vehicula metus non eleifend. Proin tempus leo magna, vitae placerat ligula scelerisque quis. Aliquam vehicula turpis faucibus nisi posuere, eget volutpat neque mollis. Etiam nec fermentum odio. Ut placerat vestibulum lorem.
						Fusce mollis quis nibh eget tincidunt. Praesent pharetra bibendum arcu a iaculis. Nam malesuada rhoncus mauris at ultricies. Sed eget tempor ex. Curabitur laoreet tristique risus et luctus. Duis tincidunt velit dictum, aliquam justo eget, tincidunt ex. Donec id efficitur est, non sodales neque. Vivamus venenatis odio non vulputate suscipit. Nam rhoncus elit vel orci faucibus, vitae euismod mi accumsan. Sed ultrices eu enim in rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam aliquam neque a ligula fermentum, eu vestibulum nisi convallis.
						Fusce congue accumsan elit, non aliquam odio porta pharetra. Aenean vitae fringilla tortor, non euismod augue. Aliquam at quam sed augue viverra sagittis sit amet at mauris. Etiam fermentum enim risus, ut egestas orci rhoncus quis. Proin elementum tincidunt sapien mollis sagittis. Praesent ut neque sit amet justo laoreet finibus. Maecenas elit sapien, ultrices in diam quis, suscipit cursus eros. Donec a eros sed elit ullamcorper maximus. In hac habitasse platea dictumst. Ut vestibulum augue et lectus scelerisque, a ornare dui porta. Ut volutpat sed nisl sed ultricies. Etiam porttitor orci vitae tincidunt sodales.
						Donec iaculis eros eu posuere feugiat. Suspendisse id ultrices dui. Cras elementum neque at urna scelerisque vehicula. Nunc congue orci nec dapibus pharetra. Quisque convallis sollicitudin mi vitae pretium. Donec justo ex, interdum id neque nec, dictum rhoncus dolor. Sed bibendum elit eget rutrum pellentesque. Mauris in ullamcorper lacus, ut elementum magna. In sit amet purus eu ipsum porttitor sagittis. Phasellus mauris mauris, sollicitudin id ornare non, vulputate finibus ligula. Phasellus mollis tempor quam ut facilisis. Cras justo sem, dictum vel nisi sit amet, vehicula ornare libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
						Vivamus rhoncus purus vitae nunc euismod, quis tristique justo vehicula. Quisque elementum quam leo, at vulputate lacus malesuada vel. Suspendisse commodo, tortor vitae dapibus imperdiet, urna enim sollicitudin tellus, vitae facilisis ligula arcu id ligula. Donec pellentesque, mi at condimentum molestie, massa enim ultricies ante, at sollicitudin enim felis ac dolor. Aliquam ac aliquam lectus. Maecenas dictum nisl lectus, sed hendrerit nibh fermentum sit amet. Quisque posuere turpis quis neque scelerisque sagittis vel dapibus libero. Praesent at nisi lacus. Fusce vulputate, dui at porttitor blandit, est felis placerat massa, sit amet sodales quam dui id velit.
						Phasellus odio orci, gravida eu lectus sit amet, aliquam elementum nulla. Sed felis lacus, semper in interdum et, tincidunt sed purus. Sed accumsan massa ex, at rhoncus nibh malesuada ac. Nulla ac ligula a odio iaculis convallis. Sed vitae dapibus libero, eu luctus felis. In vitae nunc volutpat, molestie ligula a, semper justo. Vestibulum mattis quis ex a semper. Proin semper vehicula ullamcorper. Etiam ac vestibulum neque. In euismod, diam sed posuere faucibus, velit risus dignissim ante, nec bibendum orci urna sit amet sapien. Nunc bibendum lectus eget velit dictum, quis venenatis sapien semper.
						Donec egestas dapibus ipsum sed ornare. Vestibulum ut tellus sit amet turpis tristique molestie quis sed erat. Proin suscipit lacus sed ipsum sodales consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed cursus rhoncus diam eu tempus. Aliquam aliquam convallis ligula, at auctor dolor tincidunt vitae. Donec volutpat condimentum enim, vel blandit nunc tincidunt a. Suspendisse eget feugiat felis. Proin quis ipsum odio. In at elit at nibh consequat varius
						Aliquam ornare vitae neque sed pellentesque. Nulla eget congue diam. Aenean et varius mauris, eget blandit magna. Aenean pellentesque, neque faucibus auctor hendrerit, erat leo consequat mauris, ac consectetur purus ante in sem. Nullam consectetur volutpat consequat. Ut finibus cursus ipsum, eu malesuada lacus luctus vel. Vivamus in tellus lobortis, vestibulum dolor id, rutrum lectus. Donec blandit, velit vel pulvinar mattis, orci neque ultrices augue, commodo sagittis sapien massa eu quam. Proin a felis quis felis consequat efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet neque lobortis, mollis mi porttitor, maximus tellus. Phasellus a ultricies augue. Maecenas in felis orci. Quisque ullamcorper tincidunt quam eget iaculis. Cras posuere hendrerit neque sit amet placerat. Morbi metus dolor, rutrum sed eros auctor, accumsan laoreet justo.
						Nullam consectetur eget tellus sed lacinia. Ut sed dignissim enim, eget tempus sapien. Aenean quis turpis vitae lorem fringilla blandit quis ac diam. Sed at massa rutrum, commodo massa a, fringilla risus. Sed dictum tincidunt diam, id tristique urna hendrerit at. Vivamus velit nisl, porttitor id feugiat eget, blandit vitae metus. Etiam accumsan odio ipsum, quis pulvinar enim rhoncus at. Phasellus vitae auctor ligula.
						Proin in lectus in velit euismod malesuada vitae vel ante. Nulla nisi risus, sodales at rutrum nec, euismod at purus. In efficitur nunc finibus molestie ultricies. Etiam nec lacus ligula. Ut ac nisl luctus, posuere ex vitae, maximus mi. Duis sapien nulla, ornare a finibus sed, lobortis id tellus. Curabitur massa lorem, maximus non commodo vitae, sodales non quam. Pellentesque id quam lacus. Phasellus posuere non quam eu vestibulum. Vestibulum eu ornare nulla. Duis est turpis, dictum quis rhoncus ut, scelerisque in nulla.
						Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin luctus lacinia sollicitudin. Praesent sed molestie ex. Nam non mauris eros. Nullam sit amet magna luctus, vulputate ipsum at, gravida est. Donec in hendrerit sapien. Sed a tortor mauris. Morbi varius faucibus ligula, in rhoncus tortor blandit ultrices. Donec venenatis nisl nulla, sit amet ultricies tortor dapibus eu. Duis mi lectus, vulputate id metus in, consequat vestibulum diam. Ut faucibus est a convallis porta.
						Curabitur eu ex vitae leo suscipit pulvinar non vitae augue. Aliquam pharetra mattis mauris sit amet maximus. Cras sed tristique odio. In venenatis auctor iaculis. Aenean in orci maximus eros vulputate varius sed vitae orci. Curabitur vel rutrum lectus. In vitae pellentesque urna, aliquam mattis lectus. Etiam lacinia ligula id dui porttitor bibendum.
						Phasellus fringilla est tellus, eget laoreet tellus placerat convallis. Mauris in sollicitudin diam. Aenean eu malesuada risus. Pellentesque at sagittis lectus. Proin ullamcorper tortor nec nisl iaculis, at aliquam nunc commodo. Cras ut commodo lacus. Suspendisse ac mollis mauris, in mattis ipsum. Etiam cursus sapien in ipsum tincidunt, et commodo sapien faucibus. Sed id ipsum ut nunc fermentum facilisis. Aliquam a nulla magna. Vestibulum fermentum viverra dolor sed posuere. Phasellus mi turpis, feugiat quis libero ac, tincidunt accumsan arcu.
					</div>
				</div>
				<div class="article sb_article">
					<div class="article_title sb_article_title">
						ARTICLE TITLE
						<div class="article_date sb_article_date">
							ARTICLE DATE
						</div>
					</div>
					<div class="article_content sb_article_content">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. In urna odio, semper vel odio at, sagittis ultricies sem. Mauris scelerisque, sem at venenatis finibus, lacus ex malesuada quam, quis pharetra massa odio consectetur velit. Sed odio est, venenatis sit amet efficitur nec, varius id lectus. Donec blandit nisi nec viverra mattis. Aliquam sed placerat augue. Nullam feugiat consectetur urna, vitae porta lectus imperdiet at. Quisque ut dolor maximus, mattis erat nec, ornare ante. In vitae nisi sed sem auctor porttitor.
						Vestibulum sollicitudin, eros sed facilisis cursus, nunc lorem elementum metus, at maximus nibh diam vehicula nulla. Fusce varius turpis sed gravida scelerisque. Curabitur ornare mi eu metus commodo ullamcorper. Nunc vel scelerisque nunc, id fermentum nibh. Donec sit amet accumsan odio. Nam condimentum eget velit eu volutpat. Mauris vitae dapibus metus, accumsan rhoncus leo. Praesent sit amet placerat ligula. Vivamus tincidunt, augue quis convallis iaculis, urna elit fringilla magna, ut consectetur urna justo non metus. Praesent vel justo sed orci placerat dictum in id nisl. Morbi eget urna justo.
						Donec lobortis nisl diam, vitae eleifend orci ornare id. Nullam nisi ligula, viverra vel quam vitae, laoreet efficitur ex. In interdum rhoncus sapien eu accumsan. Aliquam at leo id nibh pharetra cursus ut sed odio. Nulla id diam vitae libero vulputate commodo sit amet eget risus. Suspendisse hendrerit purus ac ipsum sollicitudin fringilla. Nulla rhoncus, dui quis fringilla tincidunt, elit ipsum finibus urna, in condimentum massa tortor eu elit. Quisque nec sem vel nibh posuere posuere nec non enim. Duis sed velit malesuada, lacinia libero eu, venenatis ante. Proin molestie molestie velit, vel ullamcorper ex eleifend sed. Etiam tincidunt tincidunt mi, vel ultrices enim lobortis eget. Curabitur nisi nunc, interdum eu tortor sed, tristique egestas est. Duis vestibulum mattis fermentum. Aenean congue porta porttitor. Donec euismod orci et eros porta, maximus tristique dolor congue.
						Nam vel faucibus nunc, quis placerat nisi. Nullam at eros eget dui semper dictum non id ipsum. In malesuada consectetur tortor, ac gravida ligula posuere ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id sodales magna. Pellentesque rhoncus sem eu dolor malesuada maximus. In congue ligula quis lectus cursus consectetur. In quis ante eros. Nam vel posuere turpis. Quisque a tempus libero. Fusce blandit velit vitae vehicula pulvinar. Pellentesque feugiat odio hendrerit, ultricies libero a, volutpat sem. Morbi consectetur est ex, nec tempus est vestibulum ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet sapien ut ipsum tincidunt dapibus et eu enim. Fusce tortor metus, aliquet sit amet mollis vel, suscipit sed tellus.
						Duis imperdiet vulputate velit in pulvinar. Nulla viverra ac elit vel malesuada. Ut non purus id elit laoreet porttitor fringilla vel arcu. Cras id purus ac tellus pellentesque scelerisque in quis mi. Duis cursus nec enim quis vestibulum. Aliquam sed lacus fermentum, commodo odio ut, tempor neque. In et sagittis dolor. Nam tellus ex, auctor ut nulla eu, tincidunt scelerisque ante. Mauris quis ante eget dolor consectetur interdum. Etiam lectus tortor, vestibulum sed consequat nec, vestibulum nec elit. Mauris aliquam aliquam molestie.
						Nunc viverra congue nisl sit amet porta. Aenean accumsan lobortis lacus vel scelerisque. Morbi eleifend quam nibh, vel suscipit lacus commodo nec. Phasellus aliquet odio ac mauris posuere tempus. Vestibulum condimentum nulla at quam fermentum egestas non at dolor. Ut sit amet mattis purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent volutpat dui id elit pretium congue. Pellentesque ac interdum ligula.
						Nullam in nunc sit amet purus mattis volutpat. Aenean gravida non mi ac lobortis. Nulla ac turpis accumsan, commodo ipsum eget, placerat sapien. Nullam nec quam id turpis dignissim ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae enim id risus pulvinar porttitor. Duis hendrerit elit sit amet felis aliquam finibus. Vestibulum ac viverra lacus, consequat dictum lorem. Nulla ornare rutrum erat sit amet tempor. Ut mauris nunc, aliquet ac lorem quis, maximus tempor nisi. Aenean turpis felis, pharetra non est et, venenatis consequat erat. Duis tempus accumsan lorem quis porttitor.
						Nunc in vulputate dui, nec finibus enim. In dignissim, turpis vel finibus ultricies, nisl nunc dignissim mi, et porta massa ipsum at turpis. Nunc et neque in nisi fringilla dignissim. Etiam maximus gravida condimentum. Phasellus vel eros lacus. Fusce sit amet eros ac sapien accumsan rutrum. Duis at libero eget nibh imperdiet pharetra. Maecenas dictum vehicula metus non eleifend. Proin tempus leo magna, vitae placerat ligula scelerisque quis. Aliquam vehicula turpis faucibus nisi posuere, eget volutpat neque mollis. Etiam nec fermentum odio. Ut placerat vestibulum lorem.
						Fusce mollis quis nibh eget tincidunt. Praesent pharetra bibendum arcu a iaculis. Nam malesuada rhoncus mauris at ultricies. Sed eget tempor ex. Curabitur laoreet tristique risus et luctus. Duis tincidunt velit dictum, aliquam justo eget, tincidunt ex. Donec id efficitur est, non sodales neque. Vivamus venenatis odio non vulputate suscipit. Nam rhoncus elit vel orci faucibus, vitae euismod mi accumsan. Sed ultrices eu enim in rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam aliquam neque a ligula fermentum, eu vestibulum nisi convallis.
						Fusce congue accumsan elit, non aliquam odio porta pharetra. Aenean vitae fringilla tortor, non euismod augue. Aliquam at quam sed augue viverra sagittis sit amet at mauris. Etiam fermentum enim risus, ut egestas orci rhoncus quis. Proin elementum tincidunt sapien mollis sagittis. Praesent ut neque sit amet justo laoreet finibus. Maecenas elit sapien, ultrices in diam quis, suscipit cursus eros. Donec a eros sed elit ullamcorper maximus. In hac habitasse platea dictumst. Ut vestibulum augue et lectus scelerisque, a ornare dui porta. Ut volutpat sed nisl sed ultricies. Etiam porttitor orci vitae tincidunt sodales.
						Donec iaculis eros eu posuere feugiat. Suspendisse id ultrices dui. Cras elementum neque at urna scelerisque vehicula. Nunc congue orci nec dapibus pharetra. Quisque convallis sollicitudin mi vitae pretium. Donec justo ex, interdum id neque nec, dictum rhoncus dolor. Sed bibendum elit eget rutrum pellentesque. Mauris in ullamcorper lacus, ut elementum magna. In sit amet purus eu ipsum porttitor sagittis. Phasellus mauris mauris, sollicitudin id ornare non, vulputate finibus ligula. Phasellus mollis tempor quam ut facilisis. Cras justo sem, dictum vel nisi sit amet, vehicula ornare libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
						Vivamus rhoncus purus vitae nunc euismod, quis tristique justo vehicula. Quisque elementum quam leo, at vulputate lacus malesuada vel. Suspendisse commodo, tortor vitae dapibus imperdiet, urna enim sollicitudin tellus, vitae facilisis ligula arcu id ligula. Donec pellentesque, mi at condimentum molestie, massa enim ultricies ante, at sollicitudin enim felis ac dolor. Aliquam ac aliquam lectus. Maecenas dictum nisl lectus, sed hendrerit nibh fermentum sit amet. Quisque posuere turpis quis neque scelerisque sagittis vel dapibus libero. Praesent at nisi lacus. Fusce vulputate, dui at porttitor blandit, est felis placerat massa, sit amet sodales quam dui id velit.
						Phasellus odio orci, gravida eu lectus sit amet, aliquam elementum nulla. Sed felis lacus, semper in interdum et, tincidunt sed purus. Sed accumsan massa ex, at rhoncus nibh malesuada ac. Nulla ac ligula a odio iaculis convallis. Sed vitae dapibus libero, eu luctus felis. In vitae nunc volutpat, molestie ligula a, semper justo. Vestibulum mattis quis ex a semper. Proin semper vehicula ullamcorper. Etiam ac vestibulum neque. In euismod, diam sed posuere faucibus, velit risus dignissim ante, nec bibendum orci urna sit amet sapien. Nunc bibendum lectus eget velit dictum, quis venenatis sapien semper.
						Donec egestas dapibus ipsum sed ornare. Vestibulum ut tellus sit amet turpis tristique molestie quis sed erat. Proin suscipit lacus sed ipsum sodales consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed cursus rhoncus diam eu tempus. Aliquam aliquam convallis ligula, at auctor dolor tincidunt vitae. Donec volutpat condimentum enim, vel blandit nunc tincidunt a. Suspendisse eget feugiat felis. Proin quis ipsum odio. In at elit at nibh consequat varius
						Aliquam ornare vitae neque sed pellentesque. Nulla eget congue diam. Aenean et varius mauris, eget blandit magna. Aenean pellentesque, neque faucibus auctor hendrerit, erat leo consequat mauris, ac consectetur purus ante in sem. Nullam consectetur volutpat consequat. Ut finibus cursus ipsum, eu malesuada lacus luctus vel. Vivamus in tellus lobortis, vestibulum dolor id, rutrum lectus. Donec blandit, velit vel pulvinar mattis, orci neque ultrices augue, commodo sagittis sapien massa eu quam. Proin a felis quis felis consequat efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet neque lobortis, mollis mi porttitor, maximus tellus. Phasellus a ultricies augue. Maecenas in felis orci. Quisque ullamcorper tincidunt quam eget iaculis. Cras posuere hendrerit neque sit amet placerat. Morbi metus dolor, rutrum sed eros auctor, accumsan laoreet justo.
						Nullam consectetur eget tellus sed lacinia. Ut sed dignissim enim, eget tempus sapien. Aenean quis turpis vitae lorem fringilla blandit quis ac diam. Sed at massa rutrum, commodo massa a, fringilla risus. Sed dictum tincidunt diam, id tristique urna hendrerit at. Vivamus velit nisl, porttitor id feugiat eget, blandit vitae metus. Etiam accumsan odio ipsum, quis pulvinar enim rhoncus at. Phasellus vitae auctor ligula.
						Proin in lectus in velit euismod malesuada vitae vel ante. Nulla nisi risus, sodales at rutrum nec, euismod at purus. In efficitur nunc finibus molestie ultricies. Etiam nec lacus ligula. Ut ac nisl luctus, posuere ex vitae, maximus mi. Duis sapien nulla, ornare a finibus sed, lobortis id tellus. Curabitur massa lorem, maximus non commodo vitae, sodales non quam. Pellentesque id quam lacus. Phasellus posuere non quam eu vestibulum. Vestibulum eu ornare nulla. Duis est turpis, dictum quis rhoncus ut, scelerisque in nulla.
						Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin luctus lacinia sollicitudin. Praesent sed molestie ex. Nam non mauris eros. Nullam sit amet magna luctus, vulputate ipsum at, gravida est. Donec in hendrerit sapien. Sed a tortor mauris. Morbi varius faucibus ligula, in rhoncus tortor blandit ultrices. Donec venenatis nisl nulla, sit amet ultricies tortor dapibus eu. Duis mi lectus, vulputate id metus in, consequat vestibulum diam. Ut faucibus est a convallis porta.
						Curabitur eu ex vitae leo suscipit pulvinar non vitae augue. Aliquam pharetra mattis mauris sit amet maximus. Cras sed tristique odio. In venenatis auctor iaculis. Aenean in orci maximus eros vulputate varius sed vitae orci. Curabitur vel rutrum lectus. In vitae pellentesque urna, aliquam mattis lectus. Etiam lacinia ligula id dui porttitor bibendum.
						Phasellus fringilla est tellus, eget laoreet tellus placerat convallis. Mauris in sollicitudin diam. Aenean eu malesuada risus. Pellentesque at sagittis lectus. Proin ullamcorper tortor nec nisl iaculis, at aliquam nunc commodo. Cras ut commodo lacus. Suspendisse ac mollis mauris, in mattis ipsum. Etiam cursus sapien in ipsum tincidunt, et commodo sapien faucibus. Sed id ipsum ut nunc fermentum facilisis. Aliquam a nulla magna. Vestibulum fermentum viverra dolor sed posuere. Phasellus mi turpis, feugiat quis libero ac, tincidunt accumsan arcu.
					</div>
				</div>
				<div id="page_switches" class="sb_page_switches">
					<div class="page_switch sb_page_switch"><a href="#">1</a></div>
					<div class="page_switch sb_page_switch"><a href="#">2</a></div>
					<div class="page_switch sb_page_switch"><a href="#">3</a></div>
					<div class="page_switch sb_page_switch"><a href="#">4</a></div>
					<div class="page_switch sb_page_switch"><a href="#">5</a></div>
				</div>
			</div>
			<div id="footer" class="sb_footer">
				FOOTER FOOTER
			</div>
		<?php } else if($_GET['action'] === 'page') { ?>
			<div id="header" class="sb_header">
				<h1>HEADER HEADER</h1>
			</div>
			<div id="headlinks" class="sb_headlinks">
				<div class="headlink sb_headlink"><a href="#">Current</a><div class="headlink_active sb_headlink_active"></div></div>
				<div class="headlink sb_headlink"><a href="#">Another</a></div>
			</div>
			<div id="content_header" class="sb_content_header">
				<h3>CONTENT HEADER</h3>
			</div>
			<div id="content" class="sb_content">
				<form>
					<label for="text_name">Label</label><input type="text" name="text_name">
					<br>
					Switch option 1 <label><input type="checkbox"><span class="switch_lever sb_switch_lever"></span></label>
					<br>
					Switch option 2<label><input type="checkbox" checked><span class="switch_lever sb_switch_lever"></span></label>
					<br>
					<input class="button sb_button" type="submit" value="Submit">
					<div class="button sb_button"><a href="/page">Go to page</a></div>
					<input class="full_button sb_full_button" type="submit" value="Login"><!-- for login box -->
					<br>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<br><br><br><br>
					<input type="file" id="myFile" name="filename">
				</form>
				<table>
					<tr><th></th><th>A</th><th>B</th><th>C</th></tr>
					<tr><td>1</td><td>A1</td><td>B1</td><td>C1</td></tr>
					<tr><td>2</td><td>A2</td><td>B2</td><td>C2</td></tr>
					<tr><td>3</td><td>A3</td><td>B3</td><td>C3</td></tr>
					<tr><td>4</td><td>A4</td><td>B4</td><td>C4</td></tr>
					<tr><td>5</td><td>A5</td><td>B5</td><td>C5</td></tr>
				</table>
			</div>
			<div id="footer" class="sb_footer">
				FOOTER FOOTER
			</div>
		<?php } else if($_GET['action'] === 'pagealt') { ?>
			<div id="header" class="sb_header sbc_red sbbc_orange">
				<h1>HEADER HEADER</h1>
			</div>
			<div id="headlinks" class="sb_headlinks sbbc_grey">
				<div class="headlink sb_headlink"><a href="#">Current</a><div class="headlink_active sb_headlink_active"></div></div>
				<div class="headlink sb_headlink"><a href="#">Another</a></div>
			</div>
			<div id="content_header" class="sb_content_header sbbc_black">
				<h3>CONTENT HEADER</h3>
			</div>
			<div id="content" class="sb_content  sbbc_black">
				<form>
					<label for="text_name">Label</label><input type="text" name="text_name">
					<br>
					Switch option 1 <label><input type="checkbox"><span class="switch_lever sb_switch_lever"></span></label>
					<br>
					Switch option 2<label><input type="checkbox" checked><span class="switch_lever sb_switch_lever"></span></label>
					<br>
					<input class="button sb_button" type="submit" value="Submit">
					<div class="button sb_button"><a href="/page">Go to page</a></div>
					<input class="full_button sb_full_button" type="submit" value="Login"><!-- for login box -->
					<br>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<div class="button button_in_row sb_button sb_button_in_row"><a href="/page">Go to page</a></div>
					<br><br><br><br>
					<input type="file" id="myFile" name="filename">
				</form>
				<style>
					table tr:nth-child(even) {
						background-color: var(--sbc-grey-800);
					}
				</style>
				<table>
					<tr><th></th><th>A</th><th>B</th><th>C</th></tr>
					<tr><td>1</td><td>A1</td><td>B1</td><td>C1</td></tr>
					<tr><td>2</td><td>A2</td><td>B2</td><td>C2</td></tr>
					<tr><td>3</td><td>A3</td><td>B3</td><td>C3</td></tr>
					<tr><td>4</td><td>A4</td><td>B4</td><td>C4</td></tr>
					<tr><td>5</td><td>A5</td><td>B5</td><td>C5</td></tr>
				</table>
			</div>
			<div id="footer" class="sb_footer">
				FOOTER FOOTER
			</div>
		<?php } else if($_GET['action'] === 'colors') { ?>
			<?php
				foreach([
					'sbc_red_50',
					'sbc_red_100',
					'sbc_red_200',
					'sbc_red_300',
					'sbc_red_400',
					'sbc_red sbc_red_500',
					'sbc_red_600',
					'sbc_red_700',
					'sbc_red_800',
					'sbc_red_900',
					'sbc_red_a100',
					'sbc_red_a200',
					'sbc_red_a400',
					'sbc_red_a700',
					'sbc_pink_50',
					'sbc_pink_100',
					'sbc_pink_200',
					'sbc_pink_300',
					'sbc_pink_400',
					'sbc_pink sbc_pink_500',
					'sbc_pink_600',
					'sbc_pink_700',
					'sbc_pink_800',
					'sbc_pink_900',
					'sbc_pink_a100',
					'sbc_pink_a200',
					'sbc_pink_a400',
					'sbc_pink_a700',
					'sbc_purple_50',
					'sbc_purple_100',
					'sbc_purple_200',
					'sbc_purple_300',
					'sbc_purple_400',
					'sbc_purple sbc_purple_500',
					'sbc_purple_600',
					'sbc_purple_700',
					'sbc_purple_800',
					'sbc_purple_900',
					'sbc_purple_a100',
					'sbc_purple_a200',
					'sbc_purple_a400',
					'sbc_purple_a700',
					'sbc_deep_purple_50',
					'sbc_deep_purple_100',
					'sbc_deep_purple_200',
					'sbc_deep_purple_300',
					'sbc_deep_purple_400',
					'sbc_deep_purple sbc_deep_purple_500',
					'sbc_deep_purple_600',
					'sbc_deep_purple_700',
					'sbc_deep_purple_800',
					'sbc_deep_purple_900',
					'sbc_deep_purple_a100',
					'sbc_deep_purple_a200',
					'sbc_deep_purple_a400',
					'sbc_deep_purple_a700',
					'sbc_indigo_50',
					'sbc_indigo_100',
					'sbc_indigo_200',
					'sbc_indigo_300',
					'sbc_indigo_400',
					'sbc_indigo sbc_indigo_500',
					'sbc_indigo_600',
					'sbc_indigo_700',
					'sbc_indigo_800',
					'sbc_indigo_900',
					'sbc_indigo_a100',
					'sbc_indigo_a200',
					'sbc_indigo_a400',
					'sbc_indigo_a700',
					'sbc_blue_50',
					'sbc_blue_100',
					'sbc_blue_200',
					'sbc_blue_300',
					'sbc_blue_400',
					'sbc_blue sbc_blue_500',
					'sbc_blue_600',
					'sbc_blue_700',
					'sbc_blue_800',
					'sbc_blue_900',
					'sbc_blue_a100',
					'sbc_blue_a200',
					'sbc_blue_a400',
					'sbc_blue_a700',
					'sbc_light_blue_50',
					'sbc_light_blue_100',
					'sbc_light_blue_200',
					'sbc_light_blue_300',
					'sbc_light_blue_400',
					'sbc_light_blue sbc_light_blue_500',
					'sbc_light_blue_600',
					'sbc_light_blue_700',
					'sbc_light_blue_800',
					'sbc_light_blue_900',
					'sbc_light_blue_a100',
					'sbc_light_blue_a200',
					'sbc_light_blue_a400',
					'sbc_light_blue_a700',
					'sbc_cyan_50',
					'sbc_cyan_100',
					'sbc_cyan_200',
					'sbc_cyan_300',
					'sbc_cyan_400',
					'sbc_cyan sbc_cyan_500',
					'sbc_cyan_600',
					'sbc_cyan_700',
					'sbc_cyan_800',
					'sbc_cyan_900',
					'sbc_cyan_a100',
					'sbc_cyan_a200',
					'sbc_cyan_a400',
					'sbc_cyan_a700',
					'sbc_teal_50',
					'sbc_teal_100',
					'sbc_teal_200',
					'sbc_teal_300',
					'sbc_teal_400',
					'sbc_teal sbc_teal_500',
					'sbc_teal_600',
					'sbc_teal_700',
					'sbc_teal_800',
					'sbc_teal_900',
					'sbc_teal_a100',
					'sbc_teal_a200',
					'sbc_teal_a400',
					'sbc_teal_a700',
					'sbc_green_50',
					'sbc_green_100',
					'sbc_green_200',
					'sbc_green_300',
					'sbc_green_400',
					'sbc_green sbc_green_500',
					'sbc_green_600',
					'sbc_green_700',
					'sbc_green_800',
					'sbc_green_900',
					'sbc_green_a100',
					'sbc_green_a200',
					'sbc_green_a400',
					'sbc_green_a700',
					'sbc_light_green_50',
					'sbc_light_green_100',
					'sbc_light_green_200',
					'sbc_light_green_300',
					'sbc_light_green_400',
					'sbc_light_green sbc_light_green_500',
					'sbc_light_green_600',
					'sbc_light_green_700',
					'sbc_light_green_800',
					'sbc_light_green_900',
					'sbc_light_green_a100',
					'sbc_light_green_a200',
					'sbc_light_green_a400',
					'sbc_light_green_a700',
					'sbc_lime_50',
					'sbc_lime_100',
					'sbc_lime_200',
					'sbc_lime_300',
					'sbc_lime_400',
					'sbc_lime sbc_lime_500',
					'sbc_lime_600',
					'sbc_lime_700',
					'sbc_lime_800',
					'sbc_lime_900',
					'sbc_lime_a100',
					'sbc_lime_a200',
					'sbc_lime_a400',
					'sbc_lime_a700',
					'sbc_yellow_50',
					'sbc_yellow_100',
					'sbc_yellow_200',
					'sbc_yellow_300',
					'sbc_yellow_400',
					'sbc_yellow sbc_yellow_500',
					'sbc_yellow_600',
					'sbc_yellow_700',
					'sbc_yellow_800',
					'sbc_yellow_900',
					'sbc_yellow_a100',
					'sbc_yellow_a200',
					'sbc_yellow_a400',
					'sbc_yellow_a700',
					'sbc_amber_50',
					'sbc_amber_100',
					'sbc_amber_200',
					'sbc_amber_300',
					'sbc_amber_400',
					'sbc_amber sbc_amber_500',
					'sbc_amber_600',
					'sbc_amber_700',
					'sbc_amber_800',
					'sbc_amber_900',
					'sbc_amber_a100',
					'sbc_amber_a200',
					'sbc_amber_a400',
					'sbc_amber_a700',
					'sbc_orange_50',
					'sbc_orange_100',
					'sbc_orange_200',
					'sbc_orange_300',
					'sbc_orange_400',
					'sbc_orange sbc_orange_500',
					'sbc_orange_600',
					'sbc_orange_700',
					'sbc_orange_800',
					'sbc_orange_900',
					'sbc_orange_a100',
					'sbc_orange_a200',
					'sbc_orange_a400',
					'sbc_orange_a700',
					'sbc_deep_orange_50',
					'sbc_deep_orange_100',
					'sbc_deep_orange_200',
					'sbc_deep_orange_300',
					'sbc_deep_orange_400',
					'sbc_deep_orange sbc_deep_orange_500',
					'sbc_deep_orange_600',
					'sbc_deep_orange_700',
					'sbc_deep_orange_800',
					'sbc_deep_orange_900',
					'sbc_deep_orange_a100',
					'sbc_deep_orange_a200',
					'sbc_deep_orange_a400',
					'sbc_deep_orange_a700',
					'sbc_brown_50',
					'sbc_brown_100',
					'sbc_brown_200',
					'sbc_brown_300',
					'sbc_brown_400',
					'sbc_brown sbc_brown_500',
					'sbc_brown_600',
					'sbc_brown_700',
					'sbc_brown_800',
					'sbc_brown_900',
					'sbc_brown_a100',
					'sbc_brown_a200',
					'sbc_brown_a400',
					'sbc_brown_a700',
					'sbc_grey_50',
					'sbc_grey_100',
					'sbc_grey_200',
					'sbc_grey_300',
					'sbc_grey_400',
					'sbc_grey sbc_grey_500',
					'sbc_grey_600',
					'sbc_grey_700',
					'sbc_grey_800',
					'sbc_grey_900',
					'sbc_grey_a100',
					'sbc_grey_a200',
					'sbc_grey_a400',
					'sbc_grey_a700',
					'sbc_blue_grey_50',
					'sbc_blue_grey_100',
					'sbc_blue_grey_200',
					'sbc_blue_grey_300',
					'sbc_blue_grey_400',
					'sbc_blue_grey sbc_blue_grey_500',
					'sbc_blue_grey_600',
					'sbc_blue_grey_700',
					'sbc_blue_grey_800',
					'sbc_blue_grey_900',
					'sbc_blue_grey_a100',
					'sbc_blue_grey_a200',
					'sbc_blue_grey_a400',
					'sbc_blue_grey_a700',
					'sbc_black',
					'sbc_white',

					'sbbc_red_50',
					'sbbc_red_100',
					'sbbc_red_200',
					'sbbc_red_300',
					'sbbc_red_400',
					'sbbc_red sbbc_red_500',
					'sbbc_red_600',
					'sbbc_red_700',
					'sbbc_red_800',
					'sbbc_red_900',
					'sbbc_red_a100',
					'sbbc_red_a200',
					'sbbc_red_a400',
					'sbbc_red_a700',
					'sbbc_pink_50',
					'sbbc_pink_100',
					'sbbc_pink_200',
					'sbbc_pink_300',
					'sbbc_pink_400',
					'sbbc_pink sbbc_pink_500',
					'sbbc_pink_600',
					'sbbc_pink_700',
					'sbbc_pink_800',
					'sbbc_pink_900',
					'sbbc_pink_a100',
					'sbbc_pink_a200',
					'sbbc_pink_a400',
					'sbbc_pink_a700',
					'sbbc_purple_50',
					'sbbc_purple_100',
					'sbbc_purple_200',
					'sbbc_purple_300',
					'sbbc_purple_400',
					'sbbc_purple sbbc_purple_500',
					'sbbc_purple_600',
					'sbbc_purple_700',
					'sbbc_purple_800',
					'sbbc_purple_900',
					'sbbc_purple_a100',
					'sbbc_purple_a200',
					'sbbc_purple_a400',
					'sbbc_purple_a700',
					'sbbc_deep_purple_50',
					'sbbc_deep_purple_100',
					'sbbc_deep_purple_200',
					'sbbc_deep_purple_300',
					'sbbc_deep_purple_400',
					'sbbc_deep_purple sbbc_deep_purple_500',
					'sbbc_deep_purple_600',
					'sbbc_deep_purple_700',
					'sbbc_deep_purple_800',
					'sbbc_deep_purple_900',
					'sbbc_deep_purple_a100',
					'sbbc_deep_purple_a200',
					'sbbc_deep_purple_a400',
					'sbbc_deep_purple_a700',
					'sbbc_indigo_50',
					'sbbc_indigo_100',
					'sbbc_indigo_200',
					'sbbc_indigo_300',
					'sbbc_indigo_400',
					'sbbc_indigo sbbc_indigo_500',
					'sbbc_indigo_600',
					'sbbc_indigo_700',
					'sbbc_indigo_800',
					'sbbc_indigo_900',
					'sbbc_indigo_a100',
					'sbbc_indigo_a200',
					'sbbc_indigo_a400',
					'sbbc_indigo_a700',
					'sbbc_blue_50',
					'sbbc_blue_100',
					'sbbc_blue_200',
					'sbbc_blue_300',
					'sbbc_blue_400',
					'sbbc_blue sbbc_blue_500',
					'sbbc_blue_600',
					'sbbc_blue_700',
					'sbbc_blue_800',
					'sbbc_blue_900',
					'sbbc_blue_a100',
					'sbbc_blue_a200',
					'sbbc_blue_a400',
					'sbbc_blue_a700',
					'sbbc_light_blue_50',
					'sbbc_light_blue_100',
					'sbbc_light_blue_200',
					'sbbc_light_blue_300',
					'sbbc_light_blue_400',
					'sbbc_light_blue sbbc_light_blue_500',
					'sbbc_light_blue_600',
					'sbbc_light_blue_700',
					'sbbc_light_blue_800',
					'sbbc_light_blue_900',
					'sbbc_light_blue_a100',
					'sbbc_light_blue_a200',
					'sbbc_light_blue_a400',
					'sbbc_light_blue_a700',
					'sbbc_cyan_50',
					'sbbc_cyan_100',
					'sbbc_cyan_200',
					'sbbc_cyan_300',
					'sbbc_cyan_400',
					'sbbc_cyan sbbc_cyan_500',
					'sbbc_cyan_600',
					'sbbc_cyan_700',
					'sbbc_cyan_800',
					'sbbc_cyan_900',
					'sbbc_cyan_a100',
					'sbbc_cyan_a200',
					'sbbc_cyan_a400',
					'sbbc_cyan_a700',
					'sbbc_teal_50',
					'sbbc_teal_100',
					'sbbc_teal_200',
					'sbbc_teal_300',
					'sbbc_teal_400',
					'sbbc_teal sbbc_teal_500',
					'sbbc_teal_600',
					'sbbc_teal_700',
					'sbbc_teal_800',
					'sbbc_teal_900',
					'sbbc_teal_a100',
					'sbbc_teal_a200',
					'sbbc_teal_a400',
					'sbbc_teal_a700',
					'sbbc_green_50',
					'sbbc_green_100',
					'sbbc_green_200',
					'sbbc_green_300',
					'sbbc_green_400',
					'sbbc_green sbbc_green_500',
					'sbbc_green_600',
					'sbbc_green_700',
					'sbbc_green_800',
					'sbbc_green_900',
					'sbbc_green_a100',
					'sbbc_green_a200',
					'sbbc_green_a400',
					'sbbc_green_a700',
					'sbbc_light_green_50',
					'sbbc_light_green_100',
					'sbbc_light_green_200',
					'sbbc_light_green_300',
					'sbbc_light_green_400',
					'sbbc_light_green sbbc_light_green_500',
					'sbbc_light_green_600',
					'sbbc_light_green_700',
					'sbbc_light_green_800',
					'sbbc_light_green_900',
					'sbbc_light_green_a100',
					'sbbc_light_green_a200',
					'sbbc_light_green_a400',
					'sbbc_light_green_a700',
					'sbbc_lime_50',
					'sbbc_lime_100',
					'sbbc_lime_200',
					'sbbc_lime_300',
					'sbbc_lime_400',
					'sbbc_lime sbbc_lime_500',
					'sbbc_lime_600',
					'sbbc_lime_700',
					'sbbc_lime_800',
					'sbbc_lime_900',
					'sbbc_lime_a100',
					'sbbc_lime_a200',
					'sbbc_lime_a400',
					'sbbc_lime_a700',
					'sbbc_yellow_50',
					'sbbc_yellow_100',
					'sbbc_yellow_200',
					'sbbc_yellow_300',
					'sbbc_yellow_400',
					'sbbc_yellow sbbc_yellow_500',
					'sbbc_yellow_600',
					'sbbc_yellow_700',
					'sbbc_yellow_800',
					'sbbc_yellow_900',
					'sbbc_yellow_a100',
					'sbbc_yellow_a200',
					'sbbc_yellow_a400',
					'sbbc_yellow_a700',
					'sbbc_amber_50',
					'sbbc_amber_100',
					'sbbc_amber_200',
					'sbbc_amber_300',
					'sbbc_amber_400',
					'sbbc_amber sbbc_amber_500',
					'sbbc_amber_600',
					'sbbc_amber_700',
					'sbbc_amber_800',
					'sbbc_amber_900',
					'sbbc_amber_a100',
					'sbbc_amber_a200',
					'sbbc_amber_a400',
					'sbbc_amber_a700',
					'sbbc_orange_50',
					'sbbc_orange_100',
					'sbbc_orange_200',
					'sbbc_orange_300',
					'sbbc_orange_400',
					'sbbc_orange sbbc_orange_500',
					'sbbc_orange_600',
					'sbbc_orange_700',
					'sbbc_orange_800',
					'sbbc_orange_900',
					'sbbc_orange_a100',
					'sbbc_orange_a200',
					'sbbc_orange_a400',
					'sbbc_orange_a700',
					'sbbc_deep_orange_50',
					'sbbc_deep_orange_100',
					'sbbc_deep_orange_200',
					'sbbc_deep_orange_300',
					'sbbc_deep_orange_400',
					'sbbc_deep_orange sbbc_deep_orange_500',
					'sbbc_deep_orange_600',
					'sbbc_deep_orange_700',
					'sbbc_deep_orange_800',
					'sbbc_deep_orange_900',
					'sbbc_deep_orange_a100',
					'sbbc_deep_orange_a200',
					'sbbc_deep_orange_a400',
					'sbbc_deep_orange_a700',
					'sbbc_brown_50',
					'sbbc_brown_100',
					'sbbc_brown_200',
					'sbbc_brown_300',
					'sbbc_brown_400',
					'sbbc_brown sbbc_brown_500',
					'sbbc_brown_600',
					'sbbc_brown_700',
					'sbbc_brown_800',
					'sbbc_brown_900',
					'sbbc_brown_a100',
					'sbbc_brown_a200',
					'sbbc_brown_a400',
					'sbbc_brown_a700',
					'sbbc_grey_50',
					'sbbc_grey_100',
					'sbbc_grey_200',
					'sbbc_grey_300',
					'sbbc_grey_400',
					'sbbc_grey sbbc_grey_500',
					'sbbc_grey_600',
					'sbbc_grey_700',
					'sbbc_grey_800',
					'sbbc_grey_900',
					'sbbc_grey_a100',
					'sbbc_grey_a200',
					'sbbc_grey_a400',
					'sbbc_grey_a700',
					'sbbc_blue_grey_50',
					'sbbc_blue_grey_100',
					'sbbc_blue_grey_200',
					'sbbc_blue_grey_300',
					'sbbc_blue_grey_400',
					'sbbc_blue_grey sbbc_blue_grey_500',
					'sbbc_blue_grey_600',
					'sbbc_blue_grey_700',
					'sbbc_blue_grey_800',
					'sbbc_blue_grey_900',
					'sbbc_blue_grey_a100',
					'sbbc_blue_grey_a200',
					'sbbc_blue_grey_a400',
					'sbbc_blue_grey_a700',
					'sbbc_black',
					'sbbc_white'
				] as $color){
					if($color === 'sbbc_black')
						$color.=' sbc_white';

					echo '<span class="'.$color.'">'.$color.'</span><br>';
				}

				foreach([
					'--sbc-red-50',
					'--sbc-red-100',
					'--sbc-red-200',
					'--sbc-red-300',
					'--sbc-red-400',
					'--sbc-red',
					'--sbc-red-500',
					'--sbc-red-600',
					'--sbc-red-700',
					'--sbc-red-800',
					'--sbc-red-900',
					'--sbc-red-a100',
					'--sbc-red-a200',
					'--sbc-red-a400',
					'--sbc-red-a700',
					'--sbc-pink-50',
					'--sbc-pink-100',
					'--sbc-pink-200',
					'--sbc-pink-300',
					'--sbc-pink-400',
					'--sbc-pink',
					'--sbc-pink-500',
					'--sbc-pink-600',
					'--sbc-pink-700',
					'--sbc-pink-800',
					'--sbc-pink-900',
					'--sbc-pink-a100',
					'--sbc-pink-a200',
					'--sbc-pink-a400',
					'--sbc-pink-a700',
					'--sbc-purple-50',
					'--sbc-purple-100',
					'--sbc-purple-200',
					'--sbc-purple-300',
					'--sbc-purple-400',
					'--sbc-purple',
					'--sbc-purple-500',
					'--sbc-purple-600',
					'--sbc-purple-700',
					'--sbc-purple-800',
					'--sbc-purple-900',
					'--sbc-purple-a100',
					'--sbc-purple-a200',
					'--sbc-purple-a400',
					'--sbc-purple-a700',
					'--sbc-deep-purple-50',
					'--sbc-deep-purple-100',
					'--sbc-deep-purple-200',
					'--sbc-deep-purple-300',
					'--sbc-deep-purple-400',
					'--sbc-deep-purple',
					'--sbc-deep-purple-500',
					'--sbc-deep-purple-600',
					'--sbc-deep-purple-700',
					'--sbc-deep-purple-800',
					'--sbc-deep-purple-900',
					'--sbc-deep-purple-a100',
					'--sbc-deep-purple-a200',
					'--sbc-deep-purple-a400',
					'--sbc-deep-purple-a700',
					'--sbc-indigo-50',
					'--sbc-indigo-100',
					'--sbc-indigo-200',
					'--sbc-indigo-300',
					'--sbc-indigo-400',
					'--sbc-indigo',
					'--sbc-indigo-500',
					'--sbc-indigo-600',
					'--sbc-indigo-700',
					'--sbc-indigo-800',
					'--sbc-indigo-900',
					'--sbc-indigo-a100',
					'--sbc-indigo-a200',
					'--sbc-indigo-a400',
					'--sbc-indigo-a700',
					'--sbc-blue-50',
					'--sbc-blue-100',
					'--sbc-blue-200',
					'--sbc-blue-300',
					'--sbc-blue-400',
					'--sbc-blue',
					'--sbc-blue-500',
					'--sbc-blue-600',
					'--sbc-blue-700',
					'--sbc-blue-800',
					'--sbc-blue-900',
					'--sbc-blue-a100',
					'--sbc-blue-a200',
					'--sbc-blue-a400',
					'--sbc-blue-a700',
					'--sbc-light-blue-50',
					'--sbc-light-blue-100',
					'--sbc-light-blue-200',
					'--sbc-light-blue-300',
					'--sbc-light-blue-400',
					'--sbc-light-blue',
					'--sbc-light-blue-500',
					'--sbc-light-blue-600',
					'--sbc-light-blue-700',
					'--sbc-light-blue-800',
					'--sbc-light-blue-900',
					'--sbc-light-blue-a100',
					'--sbc-light-blue-a200',
					'--sbc-light-blue-a400',
					'--sbc-light-blue-a700',
					'--sbc-cyan-50',
					'--sbc-cyan-100',
					'--sbc-cyan-200',
					'--sbc-cyan-300',
					'--sbc-cyan-400',
					'--sbc-cyan',
					'--sbc-cyan-500',
					'--sbc-cyan-600',
					'--sbc-cyan-700',
					'--sbc-cyan-800',
					'--sbc-cyan-900',
					'--sbc-cyan-a100',
					'--sbc-cyan-a200',
					'--sbc-cyan-a400',
					'--sbc-cyan-a700',
					'--sbc-teal-50',
					'--sbc-teal-100',
					'--sbc-teal-200',
					'--sbc-teal-300',
					'--sbc-teal-400',
					'--sbc-teal',
					'--sbc-teal-500',
					'--sbc-teal-600',
					'--sbc-teal-700',
					'--sbc-teal-800',
					'--sbc-teal-900',
					'--sbc-teal-a100',
					'--sbc-teal-a200',
					'--sbc-teal-a400',
					'--sbc-teal-a700',
					'--sbc-green-50',
					'--sbc-green-100',
					'--sbc-green-200',
					'--sbc-green-300',
					'--sbc-green-400',
					'--sbc-green',
					'--sbc-green-500',
					'--sbc-green-600',
					'--sbc-green-700',
					'--sbc-green-800',
					'--sbc-green-900',
					'--sbc-green-a100',
					'--sbc-green-a200',
					'--sbc-green-a400',
					'--sbc-green-a700',
					'--sbc-light-green-50',
					'--sbc-light-green-100',
					'--sbc-light-green-200',
					'--sbc-light-green-300',
					'--sbc-light-green-400',
					'--sbc-light-green',
					'--sbc-light-green-500',
					'--sbc-light-green-600',
					'--sbc-light-green-700',
					'--sbc-light-green-800',
					'--sbc-light-green-900',
					'--sbc-light-green-a100',
					'--sbc-light-green-a200',
					'--sbc-light-green-a400',
					'--sbc-light-green-a700',
					'--sbc-lime-50',
					'--sbc-lime-100',
					'--sbc-lime-200',
					'--sbc-lime-300',
					'--sbc-lime-400',
					'--sbc-lime',
					'--sbc-lime-500',
					'--sbc-lime-600',
					'--sbc-lime-700',
					'--sbc-lime-800',
					'--sbc-lime-900',
					'--sbc-lime-a100',
					'--sbc-lime-a200',
					'--sbc-lime-a400',
					'--sbc-lime-a700',
					'--sbc-yellow-50',
					'--sbc-yellow-100',
					'--sbc-yellow-200',
					'--sbc-yellow-300',
					'--sbc-yellow-400',
					'--sbc-yellow',
					'--sbc-yellow-500',
					'--sbc-yellow-600',
					'--sbc-yellow-700',
					'--sbc-yellow-800',
					'--sbc-yellow-900',
					'--sbc-yellow-a100',
					'--sbc-yellow-a200',
					'--sbc-yellow-a400',
					'--sbc-yellow-a700',
					'--sbc-amber-50',
					'--sbc-amber-100',
					'--sbc-amber-200',
					'--sbc-amber-300',
					'--sbc-amber-400',
					'--sbc-amber',
					'--sbc-amber-500',
					'--sbc-amber-600',
					'--sbc-amber-700',
					'--sbc-amber-800',
					'--sbc-amber-900',
					'--sbc-amber-a100',
					'--sbc-amber-a200',
					'--sbc-amber-a400',
					'--sbc-amber-a700',
					'--sbc-orange-50',
					'--sbc-orange-100',
					'--sbc-orange-200',
					'--sbc-orange-300',
					'--sbc-orange-400',
					'--sbc-orange',
					'--sbc-orange-500',
					'--sbc-orange-600',
					'--sbc-orange-700',
					'--sbc-orange-800',
					'--sbc-orange-900',
					'--sbc-orange-a100',
					'--sbc-orange-a200',
					'--sbc-orange-a400',
					'--sbc-orange-a700',
					'--sbc-deep-orange-50',
					'--sbc-deep-orange-100',
					'--sbc-deep-orange-200',
					'--sbc-deep-orange-300',
					'--sbc-deep-orange-400',
					'--sbc-deep-orange',
					'--sbc-deep-orange-500',
					'--sbc-deep-orange-600',
					'--sbc-deep-orange-700',
					'--sbc-deep-orange-800',
					'--sbc-deep-orange-900',
					'--sbc-deep-orange-a100',
					'--sbc-deep-orange-a200',
					'--sbc-deep-orange-a400',
					'--sbc-deep-orange-a700',
					'--sbc-brown-50',
					'--sbc-brown-100',
					'--sbc-brown-200',
					'--sbc-brown-300',
					'--sbc-brown-400',
					'--sbc-brown',
					'--sbc-brown-500',
					'--sbc-brown-600',
					'--sbc-brown-700',
					'--sbc-brown-800',
					'--sbc-brown-900',
					'--sbc-brown-a100',
					'--sbc-brown-a200',
					'--sbc-brown-a400',
					'--sbc-brown-a700',
					'--sbc-grey-50',
					'--sbc-grey-100',
					'--sbc-grey-200',
					'--sbc-grey-300',
					'--sbc-grey-400',
					'--sbc-grey',
					'--sbc-grey-500',
					'--sbc-grey-600',
					'--sbc-grey-700',
					'--sbc-grey-800',
					'--sbc-grey-900',
					'--sbc-grey-a100',
					'--sbc-grey-a200',
					'--sbc-grey-a400',
					'--sbc-grey-a700',
					'--sbc-blue-grey-50',
					'--sbc-blue-grey-100',
					'--sbc-blue-grey-200',
					'--sbc-blue-grey-300',
					'--sbc-blue-grey-400',
					'--sbc-blue-grey',
					'--sbc-blue-grey-500',
					'--sbc-blue-grey-600',
					'--sbc-blue-grey-700',
					'--sbc-blue-grey-800',
					'--sbc-blue-grey-900',
					'--sbc-blue-grey-a100',
					'--sbc-blue-grey-a200',
					'--sbc-blue-grey-a400',
					'--sbc-blue-grey-a700',
					'--sbc-black',
					'--sbc-white'
				] as $color){
					echo '<span style="color: var('.$color.');">'.$color.'</span><br>';
				}
			?>
		<?php } ?>
	</body>
</html>