<?php
	/*
	 * tooltip.css library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			<?php
				if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
				else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
					require __DIR__.'/../'.basename(__FILE__, '.phtml');
			?>
			body {
				background-color: #00ff00;
			}
			div {
				margin-left: 10em;
			}
		</style>
	</head>
	<body>
		<?php
			foreach(['', 'tooltip_left'] as $position)
			foreach(['', 'tooltip_animated'] as $animated)
			{
				$classes='';

				foreach(['tooltip_white', 'tooltip_gray', 'tooltip_black'] as $color)
				{
					$classes.=' '.$position.' '.$animated;

					echo '
						<div>
							<span class="tooltip '.$classes.' '.$color.'">tooltip '.$classes.' '.$color.'<span style="width: 100%;" class="tooltip_text">Tooltip text</span></span>
						</div>
						<br><br>
					';
				}
			}
		?>
	</body>
</html>